version: '3.5'
services:
  testapp:
    build:
      context: .
    depends_on:
      - testdb
      - phantomjs
    environment:
      - MIX_ENV=test
      - 'MEMOREX_API_URL=http://memorex-api:4004/api/v1'
    networks:
      - cl-exposed
      - cl-api
    ports:
      - "4001:4001"
      - "4040:4040"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - type: volume
        source: test_build
        target: /usr/src/app/_build
        volume:
          nocopy: true
      - type: volume
        source: testdeps
        target: /usr/src/app/deps
        volume:
          nocopy: true
  testdb:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=clive
    networks:
      - cl-api
  phantomjs:
    image: wernight/phantomjs:latest
    command: phantomjs --wd
    networks:
      - cl-api
networks:
  cl-exposed:
    driver: bridge
    name: cl-exposed
  cl-api:
    driver: bridge
    name: cl-api
    internal: true
volumes:
  test_build:
  testdeps:
